language: node_js
node_js:
- '6'
env:
  global:
    secure: rEmXug/HSEvmxLAt5ULALtjPRuCbD+/oziKKSOgTEkZQZ1RGA7xYdgdgMbu8GtuLCQqfRLR4t5TYXY5h/syWAiK1CARz+EigZ1UTQ6DDVq0tMWW7xP56gmu4MUSu19ZRvaPTUrJ9n/zKFqSEBQwAuqMZTZulqyZ5iPI5N83HdJFuwU51WQ+eN421bBqgErv8nq0JKL5EQut5F2PuBKOe3h77cOwEfpKxeNnx9OkOqwXy0nO2KZyGGbo1iJO2czFaT1KHnO0uzUJ+ouXno13kI67aOWJLUFJq939isRtduPRvIxdnEz0foQKFWBMNCA2Lpq3mb40QCExX/2AmfCgStgpjBl0SEGe4jj9sjBimyHAMvF+J5TGYUiJ9ec8/CBkepoBbhwVz8HC+MHTPlwkxUUhGBAaJp39YofqC2YDrfc/hOs0xh1WMD72FErNY2Zm7XX5n7LGJcHYLzcXTVzUpxo886VNZngp/iROwhzsW0mONdYKxlbmhV65o3HsxwHm97d/3oFRDzfS3dOiadmiJebOAk2tv8Q+CX632WLZ+kpGoQl8ugDSLeT9a9yoquJwnWRE313+o5W8cv/eGBkbvnPTd6cC137PUdaOW+T/R8mkpahyrVni3f1nhvnQQk7+n6i5T8ZeIeWZur3U5UqG4gfHQpmkiPz93rjCnCQXl2y8=

branches:
  only:
  - develop
  except:
  - master
script:
- npm install
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: develop
  target_branch: master
