language: node_js
node_js:
- '6'
env:
  global:
    secure: tb8y1kaIBif1iztGO88O1oDwbfRziJjc5xmG486aU1rB813qTU3BzHY/6tFesAtDqZlxL3xE5WYhH7zVj/G8QOwWOAoZ6v/tQ5O2ZczDQ5Sj6Fa2ZGPY6OJsPYVO44mClDALYQqw++BbO8N51AJCdvQCaKffLrXCD7r3UV4BdUqyg8Uf8gHq8ZDzBBN+7ekSEOmbevHpL5PhzKh0txMtXIvTbRgGFIWfFNMh6J1i7X/zed1nAkCYQklx6ChzA5Sejm0SnJEyl1UCWdaH3+WXm6ym3CjWwEMZvkz3zLrmIDwQqz7F6amiCxKLVgT8VuHbFpM9C5klFCP+alViZV0hVpnLQBQCtWlHZ3B96G9N41LMmXOYrFA4EuyRZEuSgO0kTgp0cHlNUTqAe5HvRQ1QVcLbBbkxo+SduzQybGF56DXnopGyfaqRzRO7JCSLpSFJAq+GwA7IkDkgvKWC8YUEvIosnrSYoOgaw1veCKSzoHOVHA3LnpyNQPr/v05O6Xnd9IFfM3uStKuCTqnyU4etM8IHFkvcJcI9snaH/NOvkfNF7wuBXwHzro0m8IP7lNkZk/gd4jevtkgl5MorOWj31zdNxihDcWW+YMnoZ/JXSm5MYFOjwHARKB4IQtAQnOP0jkV7rwlYpdfXadkjV1lY6e95ndF9AwkZboSQXkO7Kn0=

branches:
  only:
  - develop
  except:
  - master
script:
- npm install
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: develop
  target_branch: master
